<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TestProductLink</description>
   <name>TestProductLink</name>
   <tag></tag>
   <elementGuidId>a65780a7-8334-49a5-8f47-8c5da3c9c986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;TestComponent&quot;]/td[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
