<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>PasswordTxtBox</description>
   <name>PasswordTxtBox</name>
   <tag></tag>
   <elementGuidId>cb3f092a-c69b-4930-86b5-a9127dc9ed16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Bugzilla_password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
