<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>RestrictCheckBox</description>
   <name>RestrictCheckBox</name>
   <tag></tag>
   <elementGuidId>53ea1fcd-fdd5-4bfb-be4c-b766af4fd91f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Bugzilla_restrictlogin&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
