<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>UsernameTxtBox</description>
   <name>UsernameTxtBox</name>
   <tag></tag>
   <elementGuidId>47b2f4b9-de85-4bad-bb6a-233c2a38ad35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Bugzilla_login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
