<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>LogoutBtn</description>
   <name>LogoutBtn</name>
   <tag></tag>
   <elementGuidId>54807ae9-419b-401d-8c10-b22d79d6c3c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;header&quot;]/ul[1]/li[11]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
