<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>QuickSearchTextBox</description>
   <name>QuickSearchTextBox</name>
   <tag></tag>
   <elementGuidId>7431e27c-6078-465e-a328-2a626d14c70c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;quicksearch_main&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
